### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create an html skeleton
- [x] Set up CSS and JS files
- [x] Create Car object
- [x] Render Car object
- [x] ????
- [x] Profit
