### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Give car a rotation property
- [x] Get user input
- [x] Apply directional CSS when key is pressed for all directions
